// <auto-generated />
using AppGear.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppGear.API.Migrations
{
    [DbContext(typeof(LorawanContext))]
    [Migration("20201106213559_InicijalnaMigracija")]
    partial class InicijalnaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppGear.API.Models.Lorawan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LorawanId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Counter")
                        .HasColumnName("Counter")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnName("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnName("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnName("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Lorawan");
                });
#pragma warning restore 612, 618
        }
    }
}
