// <auto-generated />
using System;
using AppGear.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppGear.API.Migrations
{
    [DbContext(typeof(LorawanContext))]
    [Migration("20201210082405_DevicesTable")]
    partial class DevicesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppGear.API.Models.LoriotDecodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LoriotDecodedId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CycleEventsCount")
                        .HasColumnName("CycleEventsCount")
                        .HasColumnType("int");

                    b.Property<short>("CyclePeriod")
                        .HasColumnName("CyclePeriod")
                        .HasColumnType("smallint");

                    b.Property<int>("DailyCyclesCount")
                        .HasColumnName("DailyCyclesCount")
                        .HasColumnType("int");

                    b.Property<int>("DailyEventsCount")
                        .HasColumnName("DailyEventsCount")
                        .HasColumnType("int");

                    b.Property<long>("TimeStamp")
                        .HasColumnName("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnName("Date")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("LoriotDecoded");
                });

            modelBuilder.Entity("AppGear.API.Models.LoriotProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LoriotId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EUI")
                        .HasColumnName("EUI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ack")
                        .HasColumnName("ack")
                        .HasColumnType("bit");

                    b.Property<int>("bat")
                        .HasColumnName("bat")
                        .HasColumnType("int");

                    b.Property<string>("cmd")
                        .HasColumnName("cmd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data")
                        .HasColumnName("data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("encdata")
                        .HasColumnName("encdata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fcnt")
                        .HasColumnName("fcnt")
                        .HasColumnType("int");

                    b.Property<int>("port")
                        .HasColumnName("port")
                        .HasColumnType("int");

                    b.Property<long>("ts")
                        .HasColumnName("ts")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LoriotProduction");
                });

            modelBuilder.Entity("AppGear.API.Models.LoriotStatistics", b =>
                {
                    b.Property<string>("DEV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DEV_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("APP_EUI")
                        .HasColumnName("APP_EUI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APP_KEY")
                        .HasColumnName("APP_KEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEV_EUI")
                        .HasColumnName("DEV_EUI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCB_ID")
                        .HasColumnName("PCB_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DEV_ID");

                    b.ToTable("LoriotDevice");

                    b.HasData(
                        new
                        {
                            DEV_ID = "MMD1001001991",
                            APP_EUI = "050600000000FFFF",
                            APP_KEY = "0004A30B0007D5C588A783A1A7A0E3A1",
                            DEV_EUI = "0004A30B0007D5C5",
                            PCB_ID = "MMP1601003746"
                        },
                        new
                        {
                            DEV_ID = "MMD1001001992",
                            APP_EUI = "050600000000FFFF",
                            APP_KEY = "0004A30B0007932B88A783A1A7A0E3A1",
                            DEV_EUI = "0004A30B0007932B",
                            PCB_ID = "MMP1601003747"
                        },
                        new
                        {
                            DEV_ID = "MMD1001001993",
                            APP_EUI = "050600000000FFFF",
                            APP_KEY = "0004A30B0007C3BE88A783A1A7A0E3A1",
                            DEV_EUI = "0004A30B0007C3BE",
                            PCB_ID = "MMP1601003748"
                        },
                        new
                        {
                            DEV_ID = "MMD1001001994",
                            APP_EUI = "050600000000FFFF",
                            APP_KEY = "0004A30B0007FE0788A783A1A7A0E3A1",
                            DEV_EUI = "0004A30B0007FE07",
                            PCB_ID = "MMP1601003749"
                        });
                });

            modelBuilder.Entity("AppGear.API.Models.LoriotTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LoriotId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EUI")
                        .HasColumnName("EUI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ack")
                        .HasColumnName("ack")
                        .HasColumnType("bit");

                    b.Property<int>("bat")
                        .HasColumnName("bat")
                        .HasColumnType("int");

                    b.Property<string>("cmd")
                        .HasColumnName("cmd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data")
                        .HasColumnName("data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("encdata")
                        .HasColumnName("encdata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fcnt")
                        .HasColumnName("fcnt")
                        .HasColumnType("int");

                    b.Property<int>("port")
                        .HasColumnName("port")
                        .HasColumnType("int");

                    b.Property<long>("ts")
                        .HasColumnName("ts")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LoriotTest");
                });
#pragma warning restore 612, 618
        }
    }
}
